import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
import {PlaywrightMCPClientFactory} from '../src/mcp-client.mjs';
import {diagnoseFixedOutlookUpload} from './fixtures/outlook-upload-diagnostic.mjs';
const enabled=process.env.SPARKCLAW_MAIL_BROWSER_TEST==='1';
const runtime=process.env.APP_CLI_RECOVERY_RUNTIME_ROOT?pathToFileURL(path.resolve(process.env.APP_CLI_RECOVERY_RUNTIME_ROOT)+path.sep):new URL('../',import.meta.resolve('@infinimesh/app-cli-runtime/release'));
const modules={...await import(new URL('applications/mail/lib/managed-send-dom.mjs',runtime)),...await import(new URL('applications/mail/lib/workspace-attachments.mjs',runtime)),...await import(new URL('applications/mail/lib/managed-send.mjs',runtime)),verifySendAccount:async()=>{}};
for(const mode of ['approved','nonempty','badbytes','native-card'])test(`fixed no-send upload through real CLI wrapper: ${mode}`,{skip:!enabled,timeout:30000},async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'upl-diag-'));await fs.chmod(root,0o700);
 const lease=path.join(root,'lease.json');await fs.writeFile(lease,JSON.stringify({epoch:1,generation:1,activities:[{id:'fixture',kind:'read',expires_ms:Date.now()+120000}]}),{mode:0o600});
 const html=`<!doctype html><style>button{min-width:80px;min-height:30px}[contenteditable]{min-width:100px;min-height:30px}</style><button id=new>New mail</button><div data-automation-type=RibbonBottomBarContainer><button id=ribbon data-automation-type=RibbonFlyoutAnchor aria-haspopup=true aria-expanded=false aria-label="Attach files">Attach</button></div><input id=file type=file data-testid=local-computer-filein multiple hidden><script>
 window.sendClicks=0;window.uploads=0;document.getElementById('new').onclick=()=>{const root=document.createElement('div');root.innerHTML='<input aria-label="To"><input aria-label="Subject"><div contenteditable="true" aria-label="Message body">${mode==='nonempty'?'old draft':''}</div><button id=send>Send</button><button id=discard>Discard</button>';root.id='compose';root.querySelector('#send').onclick=()=>sendClicks++;root.querySelector('#discard').onclick=()=>root.remove();document.body.append(root)};
 const ribbon=document.getElementById('ribbon');ribbon.onclick=()=>{ribbon.setAttribute('aria-expanded','true');const menu=document.createElement('div');menu.setAttribute('role','menu');const action=document.createElement('button');action.setAttribute('role','menuitem');action.textContent='Browse this computer';action.onclick=()=>document.getElementById('file').click();menu.append(action);document.body.append(menu)};
 document.getElementById('file').onchange=()=>{uploads++;const compose=document.getElementById('compose');const card=document.createElement('div');card.className='outlook-card';const name=document.createElement('div');name.textContent=document.getElementById('file').files[0].name;card.append(name);const alert=document.createElement('div');alert.setAttribute('role','alert');alert.textContent='Synthetic attachment notification';if(${mode==='native-card'}){const container=document.createElement('div');container.className='av-container';card.setAttribute('aria-label',name.textContent+' 打开 158 字节 ');name.title=name.textContent;const size=document.createElement('div');size.title=size.textContent='158 字节';card.append(size);const more=document.createElement('button');more.setAttribute('aria-label','更多操作');more.textContent='…';card.append(more);container.append(card);alert.className='screenReaderOnly';alert.textContent='';alert.style='width:1px;height:1px';compose.append(container,alert);document.getElementById('file').value='';}else compose.append(card,alert)};
 </script>`;
 const server=http.createServer((req,res)=>{res.setHeader('content-type','text/html; charset=utf-8');res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 t.after(async()=>{await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true})});
 const browser=await chromium.launchServer({headless:true});const executablePath=browser.process().spawnfile;await browser.close();
 const factory=new PlaywrightMCPClientFactory({executablePath,userDataDir:path.join(root,'profile'),outputRoot:path.join(root,'mcp-output'),connectTimeoutMS:15000,extraEnv:{APP_CLI_LEASE_FILE:lease,APP_CLI_AWAITED_CODE:'1'},spawn:(command,args,options)=>{const env={...options.env};delete env.PLAYWRIGHT_MCP_EXTENSION_TOKEN;return spawn(command,[...args.filter(a=>a!=='--extension'),'--headless'],{...options,env})}});
 const client=await factory.open({token:'synthetic',sessionID:'upload-diagnostic'});t.after(()=>client.close());await client.createTaskPage();await client.execute('page.navigate',{url:`http://127.0.0.1:${server.address().port}`});
 const request=async(name,args)=>{const r=await client.rpc.request('tools/call',{name,arguments:args},25000);assert.notEqual(r.isError,true,JSON.stringify(r));const text=r.content.filter(i=>i.type==='text').map(i=>i.text).join('\n');const m=text.match(/### Result\n([\s\S]*?)(?:\n### |$)/u);assert.ok(m);return JSON.parse(m[1].trim());};
 let finalInspectBytes=0;
 const tab={attachmentSecretSlots:100,setAttachmentSecrets:async()=>{},inspect:async expression=>{if(expression.includes('const dom=function attachmentDOM'))finalInspectBytes=Buffer.byteLength(expression);assert.ok(Buffer.byteLength(expression)+1024<=32<<10);return {result:await request('browser_evaluate',{function:expression})}},click:selector=>request('browser_run_code_unsafe',{code:`/* app-cli:awaited-code:v1 */\nasync page=>{await page.locator(${JSON.stringify(selector)}).click();return true}`}),runReadCode:code=>request('browser_run_code_unsafe',{code})};
 const relative='.sparkclaw-mail-send-'+'e'.repeat(32)+'/00/SparkX-work2-acceptance.txt';await fs.mkdir(path.dirname(path.join(root,relative)),{recursive:true,mode:0o700});const bytes=await fs.readFile(new URL('fixtures/outlook-approved-attachment.txt',import.meta.url));if(mode==='badbytes')bytes[0]^=1;await fs.writeFile(path.join(root,relative),bytes,{mode:0o600});
 if(mode==='nonempty'){await assert.rejects(diagnoseFixedOutlookUpload(tab,modules,'fixture@example.invalid',root,relative),/new_composer_not_proven_empty/);}
 else {const result=await diagnoseFixedOutlookUpload(tab,modules,'fixture@example.invalid',root,relative);assert.equal(result.no_send,true);assert.equal(result.discard,true);assert.equal(result.upload_returned,mode==='native-card');if(mode==='native-card'){assert.equal(result.final_verified,true);assert.ok(finalInspectBytes>0&&finalInspectBytes+1024<=32<<10);t.diagnostic('production final inspection UTF8 bytes='+finalInspectBytes);assert.equal(result.immediate.byte_proof_matches,true);assert.equal(result.effects,1);}else if(mode==='approved'){assert.equal(result.error,'email_attachment_upload_failed');assert.equal(result.effects,1);assert.equal(result.immediate.byte_proof_matches,true);assert.equal(result.immediate.input_valid,true);assert.equal(result.immediate.alerts[0].text,'Synthetic attachment notification');assert.ok(result.immediate.contexts.length);assert.doesNotMatch(JSON.stringify(result.immediate),/SparkX-work2-acceptance/);}else {assert.equal(result.error,'email_attachment_changed');assert.equal(result.effects,0);}}
 assert.deepEqual(await request('browser_evaluate',{function:'()=>({sendClicks,uploads})'}),{sendClicks:0,uploads:['approved','native-card'].includes(mode)?1:0});
});
