package emailmanagement

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/Chiiz0/SparkClaw/services/gateway/internal/app"
	"github.com/Chiiz0/SparkClaw/services/gateway/internal/store"
)

// The retrieval budget applies to source evidence, not tokens generated by the
// model. Candidate IDs and evidence references are allocated entirely here.
func (s *Service) buildAnalysis(ctx context.Context, job app.EmailJob) (AnalysisInput, []string, int64, error) {
	if job.Kind == app.EmailJobMessageSummary || job.Kind == app.EmailJobConversationSummary {
		target, found, err := s.repository.GetEmailAnalysisTarget(ctx, job.OwnerID, job.Kind, job.TargetID)
		if err != nil {
			return AnalysisInput{}, nil, 0, err
		}
		if _, sourceOnly := target.Inputs[store.EmailSourceSummaryPolicy]; found && sourceOnly {
			return s.buildSourceSummary(ctx, job)
		}
	}
	if job.Kind == app.EmailJobClassification || job.Kind == app.EmailJobAssignment {
		return s.buildEventAnalysis(ctx, job)
	}
	input := AnalysisInput{OutputLanguage: "en", Kind: job.Kind, TargetID: job.TargetID, Evidence: []Evidence{}, Candidates: []AnalysisCandidate{}, MissingContext: []string{}}
	refs := []string{}
	if job.Kind == app.EmailJobConversationSummary {
		conversation, found, err := s.repository.GetEmailConversation(ctx, job.OwnerID, job.TargetID)
		if err != nil {
			return input, nil, 0, err
		}
		if !found {
			return input, nil, 0, errors.New("email_conversation_missing")
		}
		input.Subject, input.Participants = conversation.Title, conversation.Participants
		refs = append(refs, "conversation:"+conversation.ID)
		page, err := s.repository.ListEmailMails(ctx, store.EmailQuery{OwnerID: job.OwnerID, ConversationID: job.TargetID, Limit: 20})
		if err != nil {
			return input, nil, 0, err
		}
		if page.NextCursor != "" {
			input.MissingContext = append(input.MissingContext, "conversation_window_limited")
		}
		for _, mail := range page.Items {
			if err := s.addExplicitReplyEvidence(ctx, job.OwnerID, mail, &input, &refs); err != nil {
				return input, nil, 0, err
			}
			refs = append(refs, "mail:"+mail.ID, "summary:"+app.EmailJobMessageSummary+":"+mail.ID)
			if mail.Summary != nil && mail.Summary.Current && mail.Summary.PromptVersion == analysisPromptVersion && mail.Verification == nil {
				input.addEvidence("summary:"+mail.Summary.ID, mail.Summary.Text, 1200)
				if mail.Summary.Coverage != "complete_for_inputs" {
					input.MissingContext = append(input.MissingContext, "mail_summary_partial:"+mail.ID)
				}
			} else if err := s.addMailEvidence(ctx, job.OwnerID, mail, &input, 1200); err != nil {
				return input, nil, 0, err
			}
		}
		return finalizeInput(input, refs, 0)
	}
	mail, found, err := s.repository.GetEmailMail(ctx, job.OwnerID, job.TargetID)
	if err != nil {
		return input, nil, 0, err
	}
	if !found {
		return input, nil, 0, errors.New("email_mail_not_found")
	}
	input.SourceTime = time.Time{}
	input.Subject, input.Participants, input.CurrentConversationID = mail.Subject, mail.Participants, mail.ConversationID
	refs = append(refs, "mail:"+mail.ID)
	if err := s.addMailEvidence(ctx, job.OwnerID, mail, &input, 12000); err != nil {
		return input, nil, 0, err
	}
	if err := s.addExplicitReplyEvidence(ctx, job.OwnerID, mail, &input, &refs); err != nil {
		return input, nil, 0, err
	}
	if mail.ProviderThreadID != "" {
		input.MissingContext = append(input.MissingContext, "provider_history_limited_to_collected_members")
	}
	replyReferences := app.EmailAnalysisReferences(mail.ReplyReferences)
	if len(mail.ReplyReferences) > app.EmailAnalysisReferenceLimit {
		input.MissingContext = append(input.MissingContext, "reply_reference_window_limited")
	}
	relatedLimit := 8
	set, err := s.repository.FindEmailCandidates(ctx, store.EmailCandidateQuery{OwnerID: job.OwnerID, MailID: mail.ID, Limit: 8})
	if err != nil {
		return input, nil, 0, err
	}
	// One bounded expansion covers a sparse first retrieval; it never scans the
	// mailbox or delegates authoritative identity decisions to scripts.
	if len(set.Conversations) == 0 && len(replyReferences) > 0 {
		relatedLimit = 16
		set, err = s.repository.FindEmailCandidates(ctx, store.EmailCandidateQuery{OwnerID: job.OwnerID, MailID: mail.ID, Limit: 16})
		if err != nil {
			return input, nil, 0, err
		}
	}
	contextVersion := app.EmailContextVersion{MailID: mail.ID, Coverage: "complete_for_collected_inputs", RelatedMailIDs: []string{}, UnresolvedReferences: []string{}}
	resolved := map[string]bool{mail.MessageID: true}
	for i, related := range set.RelatedMails {
		if i >= relatedLimit {
			input.MissingContext = append(input.MissingContext, "related_mail_window_limited")
			break
		}
		refs = append(refs, "mail:"+related.ID)
		contextVersion.RelatedMailIDs = append(contextVersion.RelatedMailIDs, related.ID)
		resolved[related.MessageID] = true
		if err := s.addMailEvidence(ctx, job.OwnerID, related, &input, 700); err != nil {
			return input, nil, 0, err
		}
	}
	for _, reference := range replyReferences {
		if !resolved[reference] {
			contextVersion.UnresolvedReferences = append(contextVersion.UnresolvedReferences, reference)
			input.MissingContext = append(input.MissingContext, "unresolved_reply:"+reference)
		}
	}
	if len(contextVersion.UnresolvedReferences) > 0 {
		contextVersion.Coverage = "missing_reply_context"
	} else if len(mail.ReplyReferences) > app.EmailAnalysisReferenceLimit {
		contextVersion.Coverage = "reply_reference_window_limited"
	}
	if err := s.updateContext(ctx, job.OwnerID, mail, contextVersion); err != nil {
		return input, nil, 0, err
	}
	if job.Kind == app.EmailJobAssignment || job.Kind == app.EmailJobRelationshipCheck {
		for i, candidate := range set.Conversations {
			if i >= 8 {
				input.MissingContext = append(input.MissingContext, "candidate_window_limited")
				break
			}
			refs = append(refs, "conversation:"+candidate.ID, "summary:"+app.EmailJobConversationSummary+":"+candidate.ID)
			projected := AnalysisCandidate{ID: candidate.ID, Title: candidate.Title, Participants: candidate.Participants, Evidence: []Evidence{}}
			if candidate.Summary != nil && candidate.Summary.Current && candidate.Summary.PromptVersion == analysisPromptVersion {
				value, limited := boundedUTF8(candidate.Summary.Text, 1200)
				projected.Evidence = append(projected.Evidence, Evidence{Ref: "summary:" + candidate.Summary.ID, Text: value})
				if limited || candidate.Summary.Coverage != "complete_for_inputs" {
					input.MissingContext = append(input.MissingContext, "candidate_summary_partial:"+candidate.ID)
				}
			} else {
				page, err := s.repository.ListEmailMails(ctx, store.EmailQuery{OwnerID: job.OwnerID, ConversationID: candidate.ID, Limit: 2})
				if err != nil {
					return input, nil, 0, err
				}
				for _, member := range page.Items {
					refs = append(refs, "mail:"+member.ID)
					part := AnalysisInput{}
					if err := s.addMailEvidence(ctx, job.OwnerID, member, &part, 500); err != nil {
						return input, nil, 0, err
					}
					projected.Evidence = append(projected.Evidence, part.Evidence...)
					input.MissingContext = append(input.MissingContext, part.MissingContext...)
				}
				input.MissingContext = append(input.MissingContext, "candidate_summary_unavailable:"+candidate.ID)
			}
			input.Candidates = append(input.Candidates, projected)
		}
	}
	return finalizeInput(input, refs, set.OwnerEpoch)
}

func (s *Service) updateContext(ctx context.Context, owner string, mail app.EmailMail, next app.EmailContextVersion) error {
	slices.Sort(next.RelatedMailIDs)
	slices.Sort(next.UnresolvedReferences)
	if mail.ContextID != "" {
		previous, found, err := s.repository.GetEmailContext(ctx, owner, mail.ContextID)
		if err != nil {
			return err
		}
		if found && slices.Equal(previous.RelatedMailIDs, next.RelatedMailIDs) && slices.Equal(previous.UnresolvedReferences, next.UnresolvedReferences) && previous.Coverage == next.Coverage {
			return nil
		}
	}
	next.ID = app.NewID("context")
	cmd := command(owner, next.ID)
	_, err := s.repository.PublishEmailContext(ctx, store.EmailContextCommand{EmailCommand: cmd, Context: next})
	return s.reconcileError(ctx, cmd, err)
}

func (s *Service) addMailEvidence(ctx context.Context, owner string, mail app.EmailMail, input *AnalysisInput, bodyLimit int) error {
	if mail.RepresentationID == "" {
		input.MissingContext = append(input.MissingContext, "mail_parse_unavailable:"+mail.ID)
		return nil
	}
	representation, found, err := s.repository.GetEmailRepresentation(ctx, owner, mail.RepresentationID)
	if err != nil {
		return err
	}
	if !found {
		return errors.New("email_representation_missing")
	}
	base := "representation:" + representation.ID
	if len(representation.HeaderSignals) > 0 {
		raw, _ := json.Marshal(representation.HeaderSignals)
		input.addEvidence(base+":automation_headers", string(raw), 2200)
	}
	if len(representation.ReplyReferences) > app.EmailAnalysisReferenceLimit {
		input.MissingContext = append(input.MissingContext, "reply_reference_window_limited")
	}
	input.addEvidence(base+":headers", fmt.Sprintf("Subject: %s\nFrom: %s\nTo: %s\nCC: %s\nDate: %s\nMessage-ID: %s\nReferences (newest first): %s", representation.Subject, strings.Join(representation.From, ", "), strings.Join(representation.To, ", "), strings.Join(representation.CC, ", "), representation.SourceTime, representation.MessageID, strings.Join(app.EmailAnalysisReferences(representation.ReplyReferences), " ")), 1200)
	if input.TargetID == mail.ID {
		input.SourceTime = representation.SourceTime
	}
	body := emailModelBodyText(representation.BodyText)
	if input.Kind != app.EmailJobClassification && mail.Verification != nil {
		body = strings.ReplaceAll(body, mail.Verification.Code, "[verification code redacted]")
	}
	input.addEvidence(base+":body", body, bodyLimit)
	if representation.State != app.EmailParseReady {
		input.MissingContext = append(input.MissingContext, "source_partial:"+mail.ID)
	}
	if len(representation.Attachments) > 0 {
		input.MissingContext = append(input.MissingContext, "attachment_not_analyzed:"+mail.ID)
	}

	return nil
}

func (input *AnalysisInput) addEvidence(ref, value string, limit int) {
	text, limited := boundedUTF8(value, limit)
	input.Evidence = append(input.Evidence, Evidence{Ref: ref, Text: text})
	if limited {
		input.MissingContext = append(input.MissingContext, "evidence_truncated:"+ref)
	}
}

func finalizeInput(input AnalysisInput, refs []string, epoch int64) (AnalysisInput, []string, int64, error) {
	limited := false
	clip := func(value *string, limit int) {
		var cut bool
		*value, cut = boundedUTF8(*value, limit)
		limited = limited || cut
	}
	clip(&input.Subject, 512)
	clip(&input.ReplyInstruction, 4000)
	for i := range input.Participants {
		clip(&input.Participants[i], 254)
	}
	if len(input.Participants) > 40 {
		input.Participants = input.Participants[:40]
		limited = true
	}
	texts := []*string{}
	for i := range input.Evidence {
		texts = append(texts, &input.Evidence[i].Text)
	}
	for i := range input.Candidates {
		candidate := &input.Candidates[i]
		clip(&candidate.Title, 512)
		for p := range candidate.Participants {
			clip(&candidate.Participants[p], 254)
		}
		if len(candidate.Participants) > 20 {
			candidate.Participants = candidate.Participants[:20]
			limited = true
		}
		for e := range candidate.Evidence {
			texts = append(texts, &candidate.Evidence[e].Text)
		}
	}
	for i := range input.MissingContext {
		clip(&input.MissingContext[i], 512)
	}
	slices.Sort(input.MissingContext)
	input.MissingContext = slices.Compact(input.MissingContext)
	if len(input.MissingContext) > 28 {
		input.MissingContext = append(input.MissingContext[:27], "additional_source_gaps")
	}
	// Keep the largest evidence item shrinking until the complete serialized
	// request fits, leaving every source reference and an explicit gap marker.
	for pass := 0; pass < 512; pass++ {
		if limited && !slices.Contains(input.MissingContext, "model_context_limited") {
			input.MissingContext = append(input.MissingContext, "model_context_limited")
		}
		raw, err := json.Marshal(input)
		if err != nil {
			return input, refs, epoch, err
		}
		if len(raw) <= maxAnalysisInputBytes {
			return input, refs, epoch, nil
		}
		var largest *string
		for _, text := range texts {
			if largest == nil || len(*text) > len(*largest) {
				largest = text
			}
		}
		if largest == nil || len(*largest) < 32 {
			break
		}
		*largest, _ = boundedUTF8(*largest, len(*largest)/2)
		limited = true
	}
	return input, refs, epoch, errors.New("email_model_input_limit")
}

// A locally-sent reply may open a new interaction matter while its original
// notice keeps its old membership. The explicit user-selected source remains
// bounded context, never an inferred membership change or a recursive crawl.
func (s *Service) addExplicitReplyEvidence(ctx context.Context, owner string, mail app.EmailMail, input *AnalysisInput, refs *[]string) error {
	if mail.ReplyMailID == "" || mail.ReplyMailID == mail.ID {
		return nil
	}
	ref := "mail:" + mail.ReplyMailID
	if slices.Contains(*refs, ref) {
		return nil
	}
	original, found, err := s.repository.GetEmailMail(ctx, owner, mail.ReplyMailID)
	if err != nil {
		return err
	}
	if !found {
		input.MissingContext = append(input.MissingContext, "explicit_reply_original_unavailable")
		return nil
	}
	*refs = append(*refs, ref)
	return s.addMailEvidence(ctx, owner, original, input, 1000)
}

// buildEventAnalysis is read-only: neither retrieval nor presentation publishes
// context versions. Its dependencies describe immutable sources and membership.
func (s *Service) buildEventAnalysis(ctx context.Context, job app.EmailJob) (AnalysisInput, []string, int64, error) {
	input := AnalysisInput{PolicyVersion: analysisPromptVersion, OutputLanguage: "source", Kind: job.Kind, TargetID: job.TargetID, Evidence: []Evidence{}, Candidates: []AnalysisCandidate{}, MissingContext: []string{}}
	mail, found, err := s.repository.GetEmailMail(ctx, job.OwnerID, job.TargetID)
	if err != nil {
		return input, nil, 0, err
	}
	if !found {
		return input, nil, 0, errors.New("email_mail_not_found")
	}
	input.Subject, input.Participants = mail.Subject, slices.Clone(mail.Participants)
	refs := []string{"source:" + mail.ID}
	if err := s.addMailEvidence(ctx, job.OwnerID, mail, &input, 1200); err != nil {
		return input, nil, 0, err
	}
	if job.Kind == app.EmailJobClassification {
		input.ClassificationStage = "body"
		// Single-mail classification must never observe generated fields, reply
		// members, candidate selection, or current event membership.
		return finalizeInput(input, refs, 0)
	}
	input.CurrentConversationID = mail.ConversationID
	refs = append(refs, "mapping:"+mail.ID)
	set, err := s.repository.FindEmailCandidates(ctx, store.EmailCandidateQuery{OwnerID: job.OwnerID, MailID: mail.ID, Limit: 10})
	if err != nil {
		return input, nil, 0, err
	}
	resolved := map[string]bool{mail.MessageID: true}
	for i, related := range set.RelatedMails {
		if i >= 10 {
			input.MissingContext = append(input.MissingContext, "related_mail_window_limited")
			break
		}
		resolved[related.MessageID] = true
		refs = append(refs, "source:"+related.ID, "mapping:"+related.ID)
		if err := s.addMailEvidence(ctx, job.OwnerID, related, &input, 500); err != nil {
			return input, nil, 0, err
		}
	}
	for _, reference := range app.EmailAnalysisReferences(mail.ReplyReferences) {
		if !resolved[reference] {
			input.MissingContext = append(input.MissingContext, "unresolved_reply:"+reference)
		}
	}
	if len(mail.ReplyReferences) > app.EmailAnalysisReferenceLimit {
		input.MissingContext = append(input.MissingContext, "reply_reference_window_limited")
	}
	for i, candidate := range set.Conversations {
		if i >= 10 {
			input.MissingContext = append(input.MissingContext, "candidate_window_limited")
			break
		}
		refs = append(refs, "members:"+candidate.ID)
		projected := AnalysisCandidate{ID: candidate.ID, Evidence: []Evidence{}}
		page, err := s.repository.ListEmailMails(ctx, store.EmailQuery{OwnerID: job.OwnerID, ConversationID: candidate.ID, Limit: 2})
		if err != nil {
			return input, nil, 0, err
		}
		if page.NextCursor != "" {
			input.MissingContext = append(input.MissingContext, "candidate_members_limited:"+candidate.ID)
		}
		for _, member := range page.Items {
			refs = append(refs, "source:"+member.ID, "mapping:"+member.ID)
			part := AnalysisInput{}
			if err := s.addMailEvidence(ctx, job.OwnerID, member, &part, 500); err != nil {
				return input, nil, 0, err
			}
			projected.Evidence = append(projected.Evidence, part.Evidence...)
			input.MissingContext = append(input.MissingContext, part.MissingContext...)
		}
		input.Candidates = append(input.Candidates, projected)
	}
	// Enforce a total source text budget, keeping locations and explicit gaps.
	evidence := []*Evidence{}
	for i := range input.Evidence {
		evidence = append(evidence, &input.Evidence[i])
	}
	for i := range input.Candidates {
		for j := range input.Candidates[i].Evidence {
			evidence = append(evidence, &input.Candidates[i].Evidence[j])
		}
	}
	for {
		total := 0
		var largest *Evidence
		for _, e := range evidence {
			total += len(e.Text)
			if largest == nil || len(e.Text) > len(largest.Text) {
				largest = e
			}
		}
		if total <= 8000 || largest == nil {
			break
		}
		largest.Text, _ = boundedUTF8(largest.Text, max(0, len(largest.Text)-min(total-8000, max(1, len(largest.Text)/4))))
		input.MissingContext = append(input.MissingContext, "evidence_truncated:"+largest.Ref)
	}

	return finalizeInput(input, refs, set.OwnerEpoch)
}
