import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const script = new URL('./revivalstack.user.js', import.meta.url);
const marker = ['  // BEGIN SPARKCLAW BATCH', '  // END SPARKCLAW BATCH'];
const source = await fs.readFile(new URL('./src/timeline-batch.js', import.meta.url), 'utf8');
let text = await fs.readFile(script, 'utf8');
const block = marker[0] + '\n' + source + '\n' + marker[1];
if (text.includes(marker[0])) text = text.slice(0, text.indexOf(marker[0])) + block + text.slice(text.indexOf(marker[1]) + marker[1].length);
else text = text.replace('  // --- Global Constants ---', block + '\n\n  // --- Global Constants ---');
if (process.argv.includes('--check')) {
  if (text !== await fs.readFile(script, 'utf8')) throw new Error('Rebuild userscript: node tools/browser-userscripts/build-batch.mjs');
} else await fs.writeFile(script, text);

const corePath = new URL('./timeline-core.mjs', import.meta.url);
const core = '// Generated by build-batch.mjs; edit src/timeline-batch.js.\n' + source.slice(0, source.indexOf('function installTimelineBridge')) + '\nexport { SPARKCLAW_BATCH_PROVIDERS, batchConversation, batchCollection, discoverBatchHistory, scanBatchTimeline, batchTimelineSnapshot, runTimelineBatch };\n';
if (process.argv.includes('--check')) {
  if (core !== await fs.readFile(corePath, 'utf8')) throw new Error('Rebuild timeline-core.mjs');
} else await fs.writeFile(corePath, core);

const manifestPath = new URL('../../configs/browser-components.json', import.meta.url);
const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
const entry = manifest.scripts.find(row => row.file === 'revivalstack.user.js');
const digest = crypto.createHash('sha256').update(text).digest('hex');
if (process.argv.includes('--check')) {
  if (entry.sha256 !== digest) throw new Error('Userscript manifest checksum is stale');
} else {
  entry.sha256 = digest;
  await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
}
