// Generated by build-batch.mjs; edit src/timeline-batch.js.
// SparkClaw additions to RevivalStack (MIT).
const SPARKCLAW_BATCH_PROVIDERS = {
  chatgpt: { host: 'chatgpt.com', history: '/', path: /^\/(?:g\/[^/]+\/)?c\/([\w-]+)\/?$/ },
  claude: { host: 'claude.ai', history: '/recents', path: /^\/chat\/([\w-]+)\/?$/ },
  gemini: { host: 'gemini.google.com', history: '/app', path: /^\/(?:u\/\d+\/)?app\/([\w-]+)\/?$/ },
  grok: { host: 'grok.com', history: '/history', path: /^\/c\/([\w-]+)\/?$/ }
};
function batchConversation(provider, href) {
  try {
    const config = SPARKCLAW_BATCH_PROVIDERS[provider], url = new URL(href, 'https://' + config.host);
    const match = config.path.exec(url.pathname);
    if (url.protocol !== 'https:' || url.host !== config.host || url.username || url.password || !match) return null;
    return { id: match[1], url: url.origin + url.pathname.replace(/\/$/, '') };
  } catch { return null; }
}
async function scanBatchTimeline(provider, io) {
  const rows = new Map();
  let stable = 0;
  for (let step = 0; step < 2000; step++) {
    io.check();
    const snapshot = await io.snapshot();
    if (snapshot.blocked) throw new Error('timeline_login_or_loading_blocked');
    let added = 0;
    for (const item of snapshot.items) {
      const ref = batchConversation(provider, item.url);
      if (!ref) continue;
      const updated = Number.isFinite(Date.parse(item.updated)) ? new Date(item.updated).toISOString() : null;
      if (!rows.has(ref.id)) { rows.set(ref.id, { ...ref, title: item.title || '', updated, rank: rows.size }); added++; }
      else if (updated && (!rows.get(ref.id).updated || updated > rows.get(ref.id).updated)) rows.get(ref.id).updated = updated;
    }
    if (snapshot.end && !added && !snapshot.busy) stable++; else stable = 0;
    if (stable >= 5) {
      if (!rows.size && !snapshot.empty) throw new Error('timeline_not_found');
      return { schema: 'sparkclaw.timeline.v1', provider, coverage: 'visible-history', complete: false,
        warning: 'UI exhaustion cannot prove account-wide coverage; archived/project/hidden conversations may be absent.',
        conversations: [...rows.values()].sort((a, b) => a.updated && b.updated ? a.updated.localeCompare(b.updated) || a.id.localeCompare(b.id) : a.updated ? -1 : b.updated ? 1 : b.rank - a.rank) };
    }
    await io.advance();
  }
  throw new Error('timeline_scan_limit');
}
// Reads only rendered UI. No private website API, token, or cookie dependencies.
function batchTimelineSnapshot(provider, doc = document) {
  const roots = [...doc.querySelectorAll('nav, [role="navigation"], aside, side-navigation'), /\/recents|\/history/.test(doc.location.pathname) ? doc.querySelector('main') : null].filter(Boolean).filter((root, index, all) => !all.some((other, i) => i !== index && other.contains(root)));
  const items = [];
  for (const root of roots) {
    for (const node of root.querySelectorAll('a[href], [data-conversation-id]')) {
      const id = node.getAttribute('data-conversation-id');
      const url = node.getAttribute('href') || (provider === 'gemini' && id ? '/app/' + id : '');
      if (!url) continue;
      const row = node.closest('li, [role="listitem"]') || node;
      items.push({ url, title: node.textContent.trim(), updated: row.querySelector('time[datetime]')?.getAttribute('datetime') || row.getAttribute('data-update-time') });
    }
  }
  const scrollers = roots.flatMap(root => [root, ...root.querySelectorAll('*')]).filter(node => node.scrollHeight > node.clientHeight + 4 && node.clientHeight > 0 && /auto|scroll/.test(doc.defaultView.getComputedStyle(node).overflowY));
  const more = roots.flatMap(root => [...root.querySelectorAll('button')]).find(node => /^(load more|show more|加载更多|显示更多)$/i.test(node.textContent.trim()) && !node.disabled);
  return { items, end: !more && scrollers.every(node => node.scrollTop + node.clientHeight >= node.scrollHeight - 4),
    busy: roots.some(root => root.querySelector('[aria-busy="true"], [role="progressbar"]')),
    empty: roots.some(root => /^(no conversations|no chats|暂无对话|暂无聊天)$/i.test(root.textContent.trim())),
    blocked: !!doc.querySelector('input[type="password"]'), scrollers, more };
}
async function runTimelineBatch({ provider, timeline, ledger, capture, save, verify, commit, check, progress = () => {} }) {
  const result = { exported: [], skipped: [], failed: [] };
  if (timeline.provider !== provider || !Array.isArray(timeline.conversations)) throw new Error('timeline_invalid');
  for (const item of timeline.conversations) {
    check();
    const ref = batchConversation(provider, item.url);
    if (!ref || ref.id !== item.id) throw new Error('timeline_identity_invalid');
    const previous = ledger[item.id];
    if (previous && item.updated && previous.updated === item.updated && await verify(previous)) { result.skipped.push(item.id); continue; }
    try {
      const text = await capture(item);
      check();
      const doc = JSON.parse(text);
      if (doc.author !== provider || batchConversation(provider, doc.url)?.id !== item.id || !doc.exporter || !Array.isArray(doc.messages) || !doc.messages.length || doc.messages.some(m => !['user', 'ai'].includes(m.author) || typeof m.content !== 'string')) throw new Error('conversation_export_invalid');
      const contentBytes = new TextEncoder().encode(JSON.stringify({ title: doc.title, messages: doc.messages }));
      const contentHash = [...new Uint8Array(await crypto.subtle.digest('SHA-256', contentBytes))].map(x => x.toString(16).padStart(2, '0')).join('');
      if (previous?.contentHash === contentHash && await verify(previous)) {
        const record = { ...previous, updated: item.updated };
        await commit(item.id, record); ledger[item.id] = record;
        result.skipped.push(item.id); continue;
      }
      const receipt = await save(item, text);
      // File persistence, read-back verification, then checkpoint; failures retry.
      if (!await verify(receipt)) throw new Error('saved_file_verification_failed');
      check();
      const record = { ...receipt, contentHash, updated: item.updated, url: item.url };
      await commit(item.id, record); ledger[item.id] = record;
      result.exported.push(item.id);
    } catch (error) { result.failed.push({ id: item.id, error: error.message }); }
    progress(result);
  }
  return result;
}

export { SPARKCLAW_BATCH_PROVIDERS, batchConversation, scanBatchTimeline, batchTimelineSnapshot, runTimelineBatch };
