// Generated by build-batch.mjs; edit src/timeline-batch.js.
// SparkClaw additions to RevivalStack (MIT).
const SPARKCLAW_BATCH_PROVIDERS = {
  chatgpt: { host: 'chatgpt.com', history: '/', path: /^\/(?:g\/[^/]+\/)?c\/([\w-]+)\/?$/ },
  claude: { host: 'claude.ai', history: '/recents', path: /^\/chat\/([\w-]+)\/?$/ },
  gemini: { host: 'gemini.google.com', history: '/app', path: /^\/(?:u\/\d+\/)?app\/([\w-]+)\/?$/ },
  grok: { host: 'grok.com', history: '/history', path: /^\/c\/([\w-]+)\/?$/ }
};
function batchConversation(provider, href) {
  try {
    const config = SPARKCLAW_BATCH_PROVIDERS[provider], url = new URL(href, 'https://' + config.host);
    const match = config.path.exec(url.pathname);
    if (url.protocol !== 'https:' || url.host !== config.host || url.username || url.password || !match) return null;
    return { id: match[1], url: url.origin + url.pathname.replace(/\/$/, '') };
  } catch { return null; }
}
function batchCollection(provider, href) {
  try {
    const config = SPARKCLAW_BATCH_PROVIDERS[provider], url = new URL(href, 'https://' + config.host);
    if (url.protocol !== 'https:' || url.host !== config.host || url.username || url.password || url.search || url.hash) return null;
    // Follow only observed history/collection links, never destructive menus,
    // arbitrary external links, account selectors or guessed private APIs.
    if (!/^\/(?:projects?(?:\/[\w-]+)?|g\/[\w-]+(?:\/project)?|archived(?:-chats)?|archive|recents|history)\/?$/.test(url.pathname)) return null;
    return url.origin + url.pathname.replace(/\/$/, '');
  } catch { return null; }
}
async function scanBatchTimeline(provider, io) {
  const rows = new Map(), collections = new Set();
  let stable = 0;
  for (let step = 0; step < 2000; step++) {
    io.check();
    const snapshot = await io.snapshot();
    if (snapshot.blocked) throw new Error('timeline_login_or_loading_blocked');
    let added = 0;
    for (const href of snapshot.collections || []) { const url = batchCollection(provider, href); if (url && !collections.has(url)) { collections.add(url); added++; } }
    for (const item of snapshot.items) {
      const ref = batchConversation(provider, item.url);
      if (!ref) continue;
      const updated = Number.isFinite(Date.parse(item.updated)) ? new Date(item.updated).toISOString() : null;
      if (!rows.has(ref.id)) { rows.set(ref.id, { ...ref, title: item.title || '', updated, rank: rows.size }); added++; }
      else if (updated && (!rows.get(ref.id).updated || updated > rows.get(ref.id).updated)) rows.get(ref.id).updated = updated;
    }
    if (snapshot.end && !added && !snapshot.busy) stable++; else stable = 0;
    if (stable >= 5 && (rows.size || snapshot.empty || step >= 29)) {
      if (!rows.size && !snapshot.empty && !collections.size) throw new Error('timeline_not_found');
      return { schema: 'sparkclaw.timeline.v1', provider, coverage: 'visible-history', complete: false,
        collections: [...collections],
        warning: 'UI exhaustion cannot prove account-wide coverage; archived/project/hidden conversations may be absent.',
        conversations: [...rows.values()].sort((a, b) => a.updated && b.updated ? a.updated.localeCompare(b.updated) || a.id.localeCompare(b.id) : a.updated ? -1 : b.updated ? 1 : b.rank - a.rank) };
    }
    await io.advance();
  }
  throw new Error('timeline_scan_limit');
}
async function discoverBatchHistory(provider, initial, scanURL, check) {
  const rows = new Map(), visited = new Set(), pending = [initial];
  const sources = [], errors = [];
  while (pending.length) {
    check(); const url = pending.shift();
    if (visited.has(url)) continue;
    if (visited.size >= 1000) throw new Error('history_collection_limit');
    visited.add(url);
    try {
      const timeline = await scanURL(url);
      if (timeline.provider !== provider || !Array.isArray(timeline.conversations)) throw new Error('timeline_invalid');
      sources.push({ url, count: timeline.conversations.length, coverage: timeline.coverage });
      for (const item of timeline.conversations) {
        const ref = batchConversation(provider, item.url);
        if (!ref || ref.id !== item.id) throw new Error('timeline_identity_invalid');
        const previous = rows.get(item.id);
        if (!previous || (item.updated && (!previous.updated || item.updated > previous.updated))) rows.set(item.id, item);
      }
      for (const href of timeline.collections || []) {
        const collection = batchCollection(provider, href);
        if (collection && !visited.has(collection) && !pending.includes(collection)) pending.push(collection);
      }
    } catch (error) { check(); errors.push({url,error:error.message}); }
  }
  if (!sources.length) throw new Error(errors[0]?.error || 'timeline_not_found');
  return { schema: 'sparkclaw.timeline.v1', provider, coverage:'visible-history', complete:false,
    sources, errors, warning:'Only discovered history and collection links were scanned. Hidden archives, projects, and virtualized messages may be absent.',
    conversations:[...rows.values()].sort((a,b)=>a.updated && b.updated ? a.updated.localeCompare(b.updated) || a.id.localeCompare(b.id) : a.updated ? -1 : b.updated ? 1 : 0) };
}
// Reads only rendered UI. No private website API, token, or cookie dependencies.
function batchTimelineSnapshot(provider, doc = document) {
  const visible = node => {
    const rect = node.getBoundingClientRect(), style = doc.defaultView.getComputedStyle(node);
    return rect.width > 0 && rect.height > 0 && style.display !== 'none' && style.visibility !== 'hidden';
  };
  const roots = [...doc.querySelectorAll('nav, [role="navigation"], aside, side-navigation, [data-sidebar="sidebar"]'), !!batchCollection(provider, doc.location.href) ? doc.querySelector('main') : null].filter(Boolean).filter((root, index, all) => !all.some((other, i) => i !== index && other.contains(root)));
  const items = [];
  for (const root of roots) {
    for (const node of root.querySelectorAll('a[href], [data-conversation-id]')) {
      const id = node.getAttribute('data-conversation-id');
      const url = node.getAttribute('href') || (provider === 'gemini' && id ? '/app/' + id : '');
      if (!url) continue;
      const row = node.closest('li, [role="listitem"]') || node;
      items.push({ url, title: node.textContent.trim(), updated: row.querySelector('time[datetime]')?.getAttribute('datetime') || row.getAttribute('data-update-time') });
    }
  }
  const scrollers = roots.flatMap(root => [root, ...root.querySelectorAll('*')]).filter(node => node.scrollHeight > node.clientHeight + 4 && node.clientHeight > 0 && /auto|scroll/.test(doc.defaultView.getComputedStyle(node).overflowY));
  const more = roots.flatMap(root => [...root.querySelectorAll('button')]).find(node => /^(load more|show more|加载更多|显示更多)$/i.test(node.textContent.trim()) && !node.disabled && node.getAttribute('aria-disabled') !== 'true' && visible(node));
  const collections = roots.flatMap(root => [...root.querySelectorAll('a[href]')]).map(node => node.getAttribute('href')).filter(href => batchCollection(provider, href));
  return { items, collections, end: !more && scrollers.every(node => node.scrollTop + node.clientHeight >= node.scrollHeight - 4),
    busy: roots.some(root => [...root.querySelectorAll('[aria-busy="true"], [role="progressbar"]')].some(visible)),
    empty: roots.some(root => /^(no conversations|no chats|暂无对话|暂无聊天)$/i.test(root.textContent.trim())),
    blocked: !!doc.querySelector('input[type="password"]'), scrollers, more };
}
async function runTimelineBatch({ provider, timeline, ledger, capture, save, verify, commit, check, progress = () => {} }) {
  const result = { exported: [], skipped: [], failed: [] };
  if (timeline.provider !== provider || !Array.isArray(timeline.conversations)) throw new Error('timeline_invalid');
  for (const item of timeline.conversations) {
    check();
    const ref = batchConversation(provider, item.url);
    if (!ref || ref.id !== item.id) throw new Error('timeline_identity_invalid');
    const previous = ledger[item.id];
    if (previous && item.updated && previous.updated === item.updated && await verify(previous)) { result.skipped.push(item.id); continue; }
    try {
      const text = await capture(item);
      check();
      const doc = JSON.parse(text);
      if (doc.author !== provider || batchConversation(provider, doc.url)?.id !== item.id || !doc.exporter || !Array.isArray(doc.messages) || !doc.messages.length || doc.messages.some(m => !['user', 'ai'].includes(m.author) || typeof m.content !== 'string')) throw new Error('conversation_export_invalid');
      const contentBytes = new TextEncoder().encode(JSON.stringify({ title: doc.title, messages: doc.messages }));
      const contentHash = [...new Uint8Array(await crypto.subtle.digest('SHA-256', contentBytes))].map(x => x.toString(16).padStart(2, '0')).join('');
      if (previous?.contentHash === contentHash && await verify(previous)) {
        const record = { ...previous, updated: item.updated };
        await commit(item.id, record); ledger[item.id] = record;
        result.skipped.push(item.id); continue;
      }
      const receipt = await save(item, text);
      // File persistence, read-back verification, then checkpoint; failures retry.
      if (!await verify(receipt)) throw new Error('saved_file_verification_failed');
      check();
      const record = { ...receipt, contentHash, updated: item.updated, url: item.url };
      await commit(item.id, record); ledger[item.id] = record;
      result.exported.push(item.id);
    } catch (error) { result.failed.push({ id: item.id, error: error.message }); }
    progress(result);
  }
  return result;
}

export { SPARKCLAW_BATCH_PROVIDERS, batchConversation, batchCollection, discoverBatchHistory, scanBatchTimeline, batchTimelineSnapshot, runTimelineBatch };
