package toolhub

import (
	"github.com/Chiiz0/SparkClaw/services/gateway/internal/app"
)

func defaultDefinitions() []app.ToolDefinition {
	definitions := defaultDefinitionsBeforeDocumentFormats()
	definitions = append(definitions, documentToolDefinitions()...)
	return append(definitions, defaultDefinitionsAfterDocumentFormats()...)
}

func defaultDefinitionsBeforeDocumentFormats() []app.ToolDefinition {
	return []app.ToolDefinition{
		{
			Name:        app.ToolWorkspaceDataAccess,
			Description: "Confirm one frozen Runtime-owned workspace data access contract before protected discovery or reading.",
			InputSchema: schema("object", []string{"contract_revision", "locators", "access_class", "output_class", "request_digest", "invocation", "workflow", "return_route"}, map[string]any{
				"contract_revision": stringSchema(),
				"locators":          arraySchema(objectValueSchema()),
				"access_class": map[string]any{"type": "string", "enum": []any{
					string(app.PolicyAccessWorkspaceSourceRead), string(app.PolicyAccessWorkspaceDerivativeDisclosure),
				}},
				"output_class":   stringSchema(),
				"request_digest": stringSchema(),
				"invocation":     objectValueSchema(),
				"workflow":       objectValueSchema(),
				"return_route":   objectValueSchema(),
			}),
			OutputSchema: objectSchema([]string{"status", "request_digest"}, map[string]any{
				"status": stringSchema(), "request_digest": stringSchema(),
			}),
			Risk: app.RiskRead, RequiresApproval: false, Idempotent: true,
			TimeoutMS: 1000, Sandbox: "forbidden", Audit: "always",
		},
		{
			Name:        "observation.read",
			Description: "Read one bounded byte window from a persisted artifact owned by the current session.",
			InputSchema: schema("object", []string{"artifact_uri"}, map[string]any{
				"artifact_uri": stringSchema(),
				"offset":       map[string]any{"type": "integer", "minimum": float64(0)},
				"max_bytes":    map[string]any{"type": "integer", "minimum": float64(1), "maximum": float64(maxObservationReadBytes)},
			}),
			OutputSchema: objectSchema([]string{"artifact_uri", "offset", "max_bytes", "bytes", "total_bytes", "content", "truncated", "next_offset", "untrusted"}, map[string]any{
				"artifact_uri": stringSchema(),
				"offset":       integerSchema(),
				"max_bytes":    integerSchema(),
				"bytes":        integerSchema(),
				"total_bytes":  integerSchema(),
				"content":      stringSchema(),
				"truncated":    booleanSchema(),
				"next_offset":  integerSchema(),
				"untrusted":    booleanSchema(),
			}),
			Risk: app.RiskRead, RequiresApproval: false, Idempotent: true,
			TimeoutMS: 5000, Sandbox: "forbidden", Audit: "always",
		},
		{
			Name:        "files.search",
			Description: "Search base file names inside an allowed workspace and return bounded workspace-relative candidates.",
			InputSchema: schema("object", []string{"query"}, map[string]any{
				"query":       map[string]any{"type": "string"},
				"root":        map[string]any{"type": "string"},
				"max_results": map[string]any{"type": "number"},
			}),
			OutputSchema: objectSchema([]string{"query", "results", "count", "complete", "truncated"}, map[string]any{
				"query":     stringSchema(),
				"results":   arraySchema(objectValueSchema()),
				"count":     integerSchema(),
				"complete":  booleanSchema(),
				"truncated": booleanSchema(),
			}),
			Risk:             app.RiskRead,
			RequiresApproval: false,
			Idempotent:       true,
			TimeoutMS:        5000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "images.inspect",
			Description: "Inspect an uploaded workspace image with Fast visual semantics and, when OCR is enabled, extract verbatim in-image text as Markdown with explicit text/no-text classification. Text-bearing results retain OCR evidence, text-free results use visual understanding, and mixed images combine both.",
			InputSchema: schema("object", []string{"path"}, map[string]any{
				"path":         stringSchema(),
				"question":     stringSchema(),
				"content_type": stringSchema(),
			}),
			OutputSchema: objectSchema([]string{"status", "path", "content_type", "bytes", "summary", "untrusted"}, map[string]any{
				"status":             stringSchema(),
				"path":               stringSchema(),
				"content_type":       stringSchema(),
				"bytes":              integerSchema(),
				"width":              integerSchema(),
				"height":             integerSchema(),
				"model_content_type": stringSchema(),
				"model_bytes":        integerSchema(),
				"model_width":        integerSchema(),
				"model_height":       integerSchema(),
				"resized":            booleanSchema(),
				"resize_note":        stringSchema(),
				"fallback_policy":    stringSchema(),
				"question":           stringSchema(),
				"summary":            stringSchema(),
				"model":              stringSchema(),
				"profile":            stringSchema(),
				"lane":               stringSchema(),
				"mock":               booleanSchema(),
				"text_detected":      booleanSchema(),
				"ocr_status":         stringSchema(),
				"ocr_markdown":       stringSchema(),
				"ocr_model":          stringSchema(),
				"ocr_inference_ms":   integerSchema(),
				"ocr_warning":        stringSchema(),
				"untrusted":          booleanSchema(),
			}),
			Risk:             app.RiskRead,
			RequiresApproval: false,
			Idempotent:       true,
			TimeoutMS:        120000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		weatherLookupDefinition(),
		weatherRenderDefinition(),
		{
			Name:        "files.write_draft",
			Description: "Write a draft file inside the configured workspace draft folder.",
			InputSchema: schema("object", []string{"content"}, map[string]any{
				"path":    map[string]any{"type": "string"},
				"content": map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"path", "bytes", "status"}, map[string]any{
				"path":   stringSchema(),
				"bytes":  integerSchema(),
				"status": stringSchema(),
			}),
			Risk:             app.RiskDraft,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        3000,
			Sandbox:          "optional",
			Audit:            "always",
		},
		{
			Name:        "file.delete",
			Description: "Move a single workspace file into SparkClaw trash after explicit owner approval.",
			InputSchema: schema("object", []string{"path"}, map[string]any{
				"path":   map[string]any{"type": "string"},
				"reason": map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"status", "path", "trash_path", "manifest_path", "deleted_at"}, map[string]any{
				"status":        stringSchema(),
				"path":          stringSchema(),
				"trash_path":    stringSchema(),
				"manifest_path": stringSchema(),
				"bytes":         integerSchema(),
				"deleted_at":    stringSchema(),
			}),
			Risk:             app.RiskDangerous,
			RequiresApproval: true,
			Idempotent:       false,
			TimeoutMS:        3000,
			Sandbox:          "required",
			Audit:            "always",
		},
	}
}

func defaultDefinitionsAfterDocumentFormats() []app.ToolDefinition {
	return []app.ToolDefinition{
		{
			Name:        "memory.search",
			Description: "Search accepted private memories.",
			InputSchema: schema("object", []string{"query"}, map[string]any{
				"query": map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"query", "results", "count"}, map[string]any{
				"query":   stringSchema(),
				"results": arraySchema(objectValueSchema()),
				"count":   integerSchema(),
			}),
			Risk:             app.RiskRead,
			RequiresApproval: false,
			Idempotent:       true,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "memory.write_candidate",
			Description: "Propose a memory candidate for owner review.",
			InputSchema: schema("object", []string{"content"}, map[string]any{
				"content":     map[string]any{"type": "string"},
				"kind":        map[string]any{"type": "string"},
				"sensitivity": map[string]any{"type": "string"},
				"reason":      map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"id", "kind", "content", "sensitivity", "status", "reason", "created_at"}, map[string]any{
				"id":          stringSchema(),
				"session_id":  stringSchema(),
				"run_id":      stringSchema(),
				"kind":        stringSchema(),
				"content":     stringSchema(),
				"sensitivity": stringSchema(),
				"status":      stringSchema(),
				"reason":      stringSchema(),
				"created_at":  stringSchema(),
				"resolved_at": stringSchema(),
			}),
			Risk:             app.RiskDraft,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "memory.propose",
			Description: "Compatibility alias for proposing a memory candidate for owner review.",
			InputSchema: schema("object", []string{"content"}, map[string]any{
				"content":     map[string]any{"type": "string"},
				"kind":        map[string]any{"type": "string"},
				"sensitivity": map[string]any{"type": "string"},
				"reason":      map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"id", "kind", "content", "sensitivity", "status", "reason", "created_at"}, map[string]any{
				"id":          stringSchema(),
				"session_id":  stringSchema(),
				"run_id":      stringSchema(),
				"kind":        stringSchema(),
				"content":     stringSchema(),
				"sensitivity": stringSchema(),
				"status":      stringSchema(),
				"reason":      stringSchema(),
				"created_at":  stringSchema(),
				"resolved_at": stringSchema(),
			}),
			Risk:             app.RiskDraft,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "memory.write_sensitive",
			Description: "Write sensitive private memory only after explicit owner approval.",
			InputSchema: schema("object", []string{"content"}, map[string]any{
				"content": map[string]any{"type": "string"},
				"kind":    map[string]any{"type": "string"},
				"reason":  map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"id", "kind", "content", "source_run_id", "created_at", "sensitivity"}, map[string]any{
				"id":            stringSchema(),
				"kind":          stringSchema(),
				"content":       stringSchema(),
				"source_run_id": stringSchema(),
				"created_at":    stringSchema(),
				"sensitivity":   stringSchema(),
			}),
			Risk:             app.RiskDangerous,
			RequiresApproval: true,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "browser.read",
			Description: "Read a public HTTP(S) page through the mode-safe access path. Browser sessions use agent-browser rendered active-tab text and typed page evidence; use browser.snapshot separately for executable controls.",
			InputSchema: schema("object", []string{"url"}, map[string]any{
				"url":                     map[string]any{"type": "string"},
				"max_bytes":               map[string]any{"type": "number"},
				"timeout_ms":              map[string]any{"type": "number"},
				"browser_mode":            stringSchema(),
				"presentation":            stringSchema(),
				"surface_visible":         booleanSchema(),
				"force_browser_session":   booleanSchema(),
				"browser_session":         booleanSchema(),
				"require_browser_session": booleanSchema(),
				"reuse_active_page":       booleanSchema(),
				"disable_hidden_browser":  booleanSchema(),
				"visible_browser":         booleanSchema(),
				"owner_id":                stringSchema(),
				"browser_profile_id":      stringSchema(),
				"site_realm":              stringSchema(),
				"account_hint":            stringSchema(),
				"login_handoff_completed": booleanSchema(),
			}),
			OutputSchema: objectSchema([]string{"url", "status_code", "content_type", "title", "text", "bytes", "truncated", "untrusted", "untrusted_external_content", "warning"}, map[string]any{
				"url":                          stringSchema(),
				"status_code":                  integerSchema(),
				"status_code_source":           stringSchema(),
				"content_type":                 stringSchema(),
				"title":                        stringSchema(),
				"text":                         stringSchema(),
				"bytes":                        integerSchema(),
				"truncated":                    booleanSchema(),
				"untrusted":                    booleanSchema(),
				"untrusted_external_content":   booleanSchema(),
				"warning":                      stringSchema(),
				"extractor":                    stringSchema(),
				"readability_status":           stringSchema(),
				"readability_error":            stringSchema(),
				"readability_length":           integerSchema(),
				"readability_readerable":       booleanSchema(),
				"needs_structure_snapshot":     booleanSchema(),
				"structure_snapshot_reasons":   stringArraySchema(),
				"excerpt":                      stringSchema(),
				"byline":                       stringSchema(),
				"site_name":                    stringSchema(),
				"lang":                         stringSchema(),
				"published_time":               stringSchema(),
				"snapshot_ref":                 stringSchema(),
				"snapshot_object_key":          stringSchema(),
				"snapshot_error":               stringSchema(),
				"read_mode":                    stringSchema(),
				"browser_mode":                 stringSchema(),
				"presentation":                 stringSchema(),
				"surface_visible":              booleanSchema(),
				"rendered":                     booleanSchema(),
				"browser_provider":             stringSchema(),
				"browser_duration_ms":          integerSchema(),
				"browser_actions":              stringArraySchema(),
				"browser_read_source":          stringSchema(),
				"browser_ready_state":          stringSchema(),
				"browser_lang":                 stringSchema(),
				"browser_html_length":          integerSchema(),
				"browser_html_truncated":       booleanSchema(),
				"browser_text_length":          integerSchema(),
				"browser_text_truncated":       booleanSchema(),
				"browser_scroll_height":        integerSchema(),
				"browser_snapshot_text":        stringSchema(),
				"browser_session_error":        stringSchema(),
				"browser_session_warnings":     objectValueSchema(),
				"browser_page_auth_state":      stringSchema(),
				"browser_page_auth_confidence": stringSchema(),
				"browser_page_auth_signals":    stringArraySchema(),
				"auth_challenge_detected":      booleanSchema(),
				"auth_challenge_kind":          stringSchema(),
				"auth_site_origin":             stringSchema(),
				"auth_site_realm":              stringSchema(),
				"browser_auth_status":          stringSchema(),
				"browser_auth_strategy":        stringSchema(),
				"browser_profile_id":           stringSchema(),
				"owner_id":                     stringSchema(),
				"account_hint":                 stringSchema(),
				"login_surface":                stringSchema(),
				"login_handoff_required":       booleanSchema(),
				"login_handoff_opened":         booleanSchema(),
				"login_handoff_url":            stringSchema(),
				"login_handoff_provider":       stringSchema(),
				"login_handoff_error":          stringSchema(),
			}),
			Risk:             app.RiskRead,
			RequiresApproval: false,
			Idempotent:       true,
			TimeoutMS:        30000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "web.search",
			Description: "Search the public web as the discovery step for browser-backed research and return untrusted source evidence.",
			InputSchema: schema("object", []string{"query"}, map[string]any{
				"query":       map[string]any{"type": "string"},
				"max_results": map[string]any{"type": "number"},
				"freshness":   map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"schema_version", "request_id", "status", "query", "provider", "retrieved_at", "aggregate", "sources", "usage", "untrusted"}, map[string]any{
				"schema_version": integerSchema(),
				"request_id":     stringSchema(),
				"status":         stringSchema(),
				"query":          stringSchema(),
				"provider":       stringSchema(),
				"retrieved_at":   stringSchema(),
				"took_ms":        integerSchema(),
				"aggregate":      objectValueSchema(),
				"sources":        arraySchema(objectValueSchema()),
				"usage":          objectValueSchema(),
				"untrusted":      booleanSchema(),
			}),
			Risk:             app.RiskRead,
			RequiresApproval: false,
			Idempotent:       true,
			TimeoutMS:        30000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "browser.identify_public_target",
			Description: "Select the first provider-ranked structured Info result URL that passes mandatory public HTTPS and redirect validation.",
			InputSchema: schema("object", nil, map[string]any{}),
			OutputSchema: objectSchema([]string{"status", "evidence_id", "resolution_source", "owner_target_phrase", "requested_surface_kind", "info_result_index", "source_result_ref", "canonical_entry_url", "normalized_final_url", "safety_gate_status", "created_at", "untrusted"}, map[string]any{
				"status":                  stringSchema(),
				"evidence_id":             stringSchema(),
				"resolution_source":       stringSchema(),
				"owner_target_phrase":     stringSchema(),
				"requested_surface_kind":  stringSchema(),
				"info_request_id":         stringSchema(),
				"info_result_index":       integerSchema(),
				"source_result_ref":       stringSchema(),
				"canonical_entry_url":     stringSchema(),
				"normalized_final_url":    stringSchema(),
				"observed_redirect_chain": stringArraySchema(),
				"safety_gate_status":      stringSchema(),
				"created_at":              stringSchema(),
				"untrusted":               booleanSchema(),
			}),
			Risk: app.RiskRead, RequiresApproval: false, Idempotent: true,
			TimeoutMS: 10000, Sandbox: "forbidden", Audit: "always",
		},
		{
			Name:        "browser.visual_inspect",
			Description: "Capture and inspect one fresh generation-bound browser screenshot, then revalidate structured page identity after Fast inference.",
			InputSchema: schema("object", []string{"page_id", "snapshot_id", "session_generation", "page_generation", "snapshot_digest", "reason"}, map[string]any{
				"page_id": map[string]any{"type": []any{"string", "number"}}, "snapshot_id": stringSchema(),
				"session_generation": map[string]any{"type": []any{"string", "number"}},
				"page_generation":    map[string]any{"type": []any{"string", "number"}},
				"snapshot_digest":    stringSchema(), "reason": stringSchema(), "question": stringSchema(),
				"browser_mode": stringSchema(), "presentation": stringSchema(), "surface_visible": booleanSchema(),
			}),
			OutputSchema: objectSchema([]string{"status", "evidence_id", "reason", "session_generation", "page_generation", "page_id", "snapshot_id", "snapshot_digest", "post_snapshot_id", "normalized_url", "screenshot_ref", "screenshot_digest", "summary", "model", "profile", "lane", "created_at", "untrusted"}, map[string]any{
				"status": stringSchema(), "evidence_id": stringSchema(), "reason": stringSchema(),
				"session_generation": integerSchema(), "page_generation": integerSchema(), "page_id": stringSchema(),
				"snapshot_id": stringSchema(), "snapshot_digest": stringSchema(), "post_snapshot_id": stringSchema(),
				"normalized_url": stringSchema(), "screenshot_ref": stringSchema(), "screenshot_digest": stringSchema(),
				"summary": stringSchema(), "model": stringSchema(), "profile": stringSchema(), "lane": stringSchema(),
				"created_at": stringSchema(), "untrusted": booleanSchema(),
			}),
			Risk: app.RiskRead, RequiresApproval: false, Idempotent: true,
			TimeoutMS: 125000, Sandbox: "forbidden", Audit: "always",
		},
		browserAutomationDefinition("browser.status", "Check whether the managed agent-browser automation adapter is available.", app.RiskRead, false, nil, nil, []string{"tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.list_tabs", "List tabs/pages in the managed agent-browser Chromium session.", app.RiskRead, false, nil, nil, []string{"tool", "output", "pages", "untrusted", "provider"}),
		browserAutomationDefinition("browser.open", "Open a URL in a managed agent-browser Chromium page/tab.", app.RiskRead, false, []string{"url"}, nil, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.focus", "Focus/select a browser page/tab by stable page identifier.", app.RiskRead, false, []string{"page_id"}, nil, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.close", "Close a managed Chromium tab opened by the active Workflow, using its stable page identifier.", app.RiskDraft, false, []string{"page_id"}, nil, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.navigate", "Navigate the current or selected tab to a URL while preserving browser context.", app.RiskRead, false, []string{"url"}, []string{"page_id"}, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.snapshot", "Take a structured page snapshot for reading and stable element refs.", app.RiskRead, false, nil, []string{"page_id", "interaction_goal", "url", "browser_page_ref", "verbose", "filePath"}, []string{"tool", "raw_tool", "output", "text", "untrusted", "provider"}),
		browserAutomationDefinition("browser.screenshot", "Take a browser screenshot for visual confirmation.", app.RiskRead, false, nil, nil, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.wait", "Wait for visible text or observable page state before continuing.", app.RiskRead, false, nil, []string{"page_id", "text"}, []string{"tool", "raw_tool", "output", "text", "untrusted", "provider"}),
		browserAutomationDefinition("browser.click", "Click a clear element ref from the latest browser snapshot.", app.RiskDraft, false, []string{"uid"}, []string{"page_id", "snapshot_id", "expected_effect"}, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		{
			Name:        "browser.validate_transition",
			Description: "Deterministically validate one before/click/after browser transition without deciding whether the owner goal is satisfied.",
			InputSchema: schema("object", []string{"before_snapshot_id", "after_snapshot_id", "element_ref"}, map[string]any{
				"schema_version":     integerSchema(),
				"before_snapshot_id": stringSchema(),
				"after_snapshot_id":  stringSchema(),
				"element_ref":        stringSchema(),
			}),
			OutputSchema: objectSchema([]string{"schema_version", "status", "code", "before_snapshot_id", "after_snapshot_id", "state_changed", "session_generation"}, map[string]any{
				"schema_version":     integerSchema(),
				"status":             stringSchema(),
				"code":               stringSchema(),
				"before_snapshot_id": stringSchema(),
				"after_snapshot_id":  stringSchema(),
				"page_id":            stringSchema(),
				"element_ref":        stringSchema(),
				"session_generation": integerSchema(),
				"state_changed":      booleanSchema(),
				"before_digest":      stringSchema(),
				"after_digest":       stringSchema(),
				"click_count":        integerSchema(),
			}),
			Risk: app.RiskRead, RequiresApproval: false, Idempotent: true,
			TimeoutMS: 5000, Sandbox: "forbidden", Audit: "always",
		},
		{
			Name:        "browser.assess_goal",
			Description: "Assess the frozen browser goal against one current snapshot using explicit snapshot-owned evidence citations. A matching clickable control proves only that a next action is available, so use progress until current page state proves the requested effect. Use satisfied, success, or succeeded only when the cited snapshot proves the frozen goal is met.",
			InputSchema: schema("object", []string{"snapshot_id", "verdict", "evidence_refs"}, map[string]any{
				"snapshot_id":   stringSchema(),
				"verdict":       map[string]any{"type": "string", "enum": []any{"satisfied", "success", "succeeded", "progress", "failure"}},
				"evidence_refs": stringArraySchema(),
				"reason":        stringSchema(),
			}),
			OutputSchema: objectSchema([]string{"schema_version", "status", "code", "snapshot_id", "goal_satisfied", "evidence_refs", "reason_code"}, map[string]any{
				"schema_version":     integerSchema(),
				"status":             stringSchema(),
				"code":               stringSchema(),
				"snapshot_id":        stringSchema(),
				"page_id":            stringSchema(),
				"session_generation": integerSchema(),
				"goal_satisfied":     booleanSchema(),
				"evidence_refs":      stringArraySchema(),
				"reason":             stringSchema(),
				"reason_code":        stringSchema(),
				"click_count":        integerSchema(),
			}),
			Risk: app.RiskRead, RequiresApproval: false, Idempotent: true,
			TimeoutMS: 5000, Sandbox: "forbidden", Audit: "always",
		},
		browserAutomationDefinition("browser.type", "Fill one ordinary draftable field using a ref from the latest bound snapshot.", app.RiskDraft, true, []string{"uid", "page_id", "snapshot_id", "session_generation", "page_generation", "text"}, nil, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		browserAutomationDefinition("browser.select", "Select one ordinary reversible value using a ref from the latest bound snapshot.", app.RiskDraft, true, []string{"uid", "page_id", "snapshot_id", "session_generation", "page_generation", "value"}, nil, []string{"tool", "raw_tool", "output", "untrusted", "provider"}),
		{
			Name:        "shell.exec_sandboxed",
			Description: "Request sandboxed shell execution. MVP queues this for approval and does not execute automatically.",
			InputSchema: schema("object", []string{"command"}, map[string]any{
				"command":    map[string]any{"type": "string"},
				"timeout_ms": map[string]any{"type": "number"},
			}),
			OutputSchema: objectSchema([]string{"status", "backend", "network", "stdout", "stderr"}, map[string]any{
				"status":  stringSchema(),
				"backend": stringSchema(),
				"network": stringSchema(),
				"stdout":  stringSchema(),
				"stderr":  stringSchema(),
			}),
			Risk:             app.RiskDangerous,
			RequiresApproval: true,
			Idempotent:       false,
			TimeoutMS:        10000,
			Sandbox:          "required",
			Audit:            "always",
		},
		{
			Name:        "notify.ask_approval",
			Description: "Create an approval request for a pending action.",
			InputSchema: schema("object", []string{"summary"}, map[string]any{
				"summary": map[string]any{"type": "string"},
				"reason":  map[string]any{"type": "string"},
			}),
			OutputSchema: objectSchema([]string{"status", "approval_id", "tool_call"}, map[string]any{
				"status":      stringSchema(),
				"approval_id": stringSchema(),
				"tool_call":   stringSchema(),
			}),
			Risk:             app.RiskDraft,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "reminders.create",
			Description: "Create a scheduled owner request. At the due time it re-enters Agent routing and returns the result to the selected reminder endpoint. Default to the current external chat endpoint, otherwise web.",
			InputSchema: schema("object", []string{"text", "due_time"}, map[string]any{
				"text":       stringSchema(),
				"due_time":   stringSchema(),
				"timezone":   stringSchema(),
				"channel":    stringSchema(),
				"recipient":  stringSchema(),
				"recurrence": stringSchema(),
				"dedupe_key": stringSchema(),
			}),
			OutputSchema:     reminderOutputSchema(),
			Risk:             app.RiskReversible,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "reminders.list",
			Description: "List local reminders by optional status and time range.",
			InputSchema: schema("object", []string{}, map[string]any{
				"status":    stringSchema(),
				"from_time": stringSchema(),
				"to_time":   stringSchema(),
				"limit":     map[string]any{"type": "number"},
			}),
			OutputSchema: objectSchema([]string{"reminders", "count"}, map[string]any{
				"reminders": arraySchema(objectValueSchema()),
				"count":     integerSchema(),
			}),
			Risk:             app.RiskRead,
			RequiresApproval: false,
			Idempotent:       true,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "reminders.update",
			Description: "Update a pending local reminder without sending it immediately.",
			InputSchema: schema("object", []string{"reminder_id", "expected_updated_at"}, map[string]any{
				"reminder_id":         stringSchema(),
				"expected_updated_at": stringSchema(),
				"text":                stringSchema(),
				"due_time":            stringSchema(),
				"timezone":            stringSchema(),
				"channel":             stringSchema(),
				"recipient":           stringSchema(),
				"recurrence":          stringSchema(),
			}),
			OutputSchema:     reminderOutputSchema(),
			Risk:             app.RiskReversible,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
		{
			Name:        "reminders.cancel",
			Description: "Cancel a pending local reminder.",
			InputSchema: schema("object", []string{"reminder_id", "expected_updated_at"}, map[string]any{
				"reminder_id":         stringSchema(),
				"expected_updated_at": stringSchema(),
				"reason":              stringSchema(),
			}),
			OutputSchema:     reminderOutputSchema(),
			Risk:             app.RiskReversible,
			RequiresApproval: false,
			Idempotent:       false,
			TimeoutMS:        1000,
			Sandbox:          "forbidden",
			Audit:            "always",
		},
	}
}

func reminderOutputSchema() map[string]any {
	return objectSchema([]string{"reminder_id", "text", "text_summary", "due_time", "timezone", "channel", "status", "updated_at"}, map[string]any{
		"reminder_id":      stringSchema(),
		"text":             stringSchema(),
		"text_summary":     stringSchema(),
		"due_time":         stringSchema(),
		"timezone":         stringSchema(),
		"channel":          stringSchema(),
		"recurrence":       stringSchema(),
		"recipient":        stringSchema(),
		"status":           stringSchema(),
		"created_at":       stringSchema(),
		"updated_at":       stringSchema(),
		"canceled_at":      stringSchema(),
		"last_delivery_id": stringSchema(),
		"last_error":       stringSchema(),
	})
}
