#!/usr/bin/env sh

SPARKCLAW_ROOT=""
SPARKCLAW_SEARCH_DIR="$(pwd)"

while [ "$SPARKCLAW_SEARCH_DIR" != "/" ]; do
  if [ -f "$SPARKCLAW_SEARCH_DIR/go.work" ] && [ -f "$SPARKCLAW_SEARCH_DIR/package.json" ] && [ -d "$SPARKCLAW_SEARCH_DIR/.tools" ]; then
    SPARKCLAW_ROOT="$SPARKCLAW_SEARCH_DIR"
    break
  fi
  SPARKCLAW_SEARCH_DIR="$(dirname -- "$SPARKCLAW_SEARCH_DIR")"
done

if [ -z "$SPARKCLAW_ROOT" ]; then
  echo "SparkClaw repo root with .tools was not found."
  return 1 2>/dev/null || exit 1
fi

export PATH="$SPARKCLAW_ROOT/.tools/node-v24.14.0-darwin-arm64/bin:$SPARKCLAW_ROOT/.tools/go1.25.5/bin:$PATH"
export GOCACHE="$SPARKCLAW_ROOT/.tools/go-cache"
export GOMODCACHE="$SPARKCLAW_ROOT/.tools/go-mod-cache"

export SPARKCLAW_MODEL_MODE="${SPARKCLAW_MODEL_MODE:-external}"
export SPARKCLAW_MODEL_DISABLE_THINKING="${SPARKCLAW_MODEL_DISABLE_THINKING:-true}"
export SPARKCLAW_FAST_BASE_URL="${SPARKCLAW_FAST_BASE_URL:-https://sparkclaw.infinimesh.cloud/fast/v1}"
export SPARKCLAW_FAST_MODEL="${SPARKCLAW_FAST_MODEL:-sparkclaw-fast}"
export SPARKCLAW_FAST_SERVED_NAME="${SPARKCLAW_FAST_SERVED_NAME:-sparkclaw-fast}"
export SPARKCLAW_DEEP_BASE_URL="${SPARKCLAW_DEEP_BASE_URL:-https://sparkclaw.infinimesh.cloud/deep/v1}"
export SPARKCLAW_DEEP_MODEL="${SPARKCLAW_DEEP_MODEL:-sparkclaw-deep}"
export SPARKCLAW_DEEP_SERVED_NAME="${SPARKCLAW_DEEP_SERVED_NAME:-sparkclaw-deep}"
export SPARKCLAW_EMBEDDING_BASE_URL="${SPARKCLAW_EMBEDDING_BASE_URL:-https://sparkclaw.infinimesh.cloud/embedding/v1}"
export SPARKCLAW_EMBEDDING_MODEL="${SPARKCLAW_EMBEDDING_MODEL:-sparkclaw-embedding}"
export SPARKCLAW_RERANKER_BASE_URL="${SPARKCLAW_RERANKER_BASE_URL:-https://sparkclaw.infinimesh.cloud/reranker/v1}"
export SPARKCLAW_RERANKER_MODEL="${SPARKCLAW_RERANKER_MODEL:-sparkclaw-reranker}"
export SPARKCLAW_BROWSER_AUTOMATION_ENABLED="${SPARKCLAW_BROWSER_AUTOMATION_ENABLED:-true}"
export SPARKCLAW_BROWSER_PROFILE_DIR="${SPARKCLAW_BROWSER_PROFILE_DIR:-$SPARKCLAW_ROOT/data/browser-profiles}"
export SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED="${SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED:-true}"
export SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER="${SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER:-openclaw-weixin-qr}"
export SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL="${SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL:-https://ilinkai.weixin.qq.com}"

if [ -f "$SPARKCLAW_ROOT/.env" ]; then
  SPARKCLAW_BROWSER_AUTOMATION_ENABLED_LINE="$(grep -E '^SPARKCLAW_BROWSER_AUTOMATION_ENABLED=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_BROWSER_CHROMIUM_EXECUTABLE_LINE="$(grep -E '^SPARKCLAW_BROWSER_CHROMIUM_EXECUTABLE=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_BROWSER_PROFILE_DIR_LINE="$(grep -E '^SPARKCLAW_BROWSER_PROFILE_DIR=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED_LINE="$(grep -E '^SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER_LINE="$(grep -E '^SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL_LINE="$(grep -E '^SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_WEB_SEARCH_ENABLED_LINE="$(grep -E '^SPARKCLAW_WEB_SEARCH_ENABLED=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_WEB_SEARCH_PROVIDER_LINE="$(grep -E '^SPARKCLAW_WEB_SEARCH_PROVIDER=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_PARALLEL_BASE_URL_LINE="$(grep -E '^SPARKCLAW_PARALLEL_BASE_URL=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  SPARKCLAW_PARALLEL_MAX_RESULTS_LINE="$(grep -E '^SPARKCLAW_PARALLEL_MAX_RESULTS=' "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
  if [ -n "$SPARKCLAW_BROWSER_AUTOMATION_ENABLED_LINE" ]; then
    export SPARKCLAW_BROWSER_AUTOMATION_ENABLED="${SPARKCLAW_BROWSER_AUTOMATION_ENABLED_LINE#SPARKCLAW_BROWSER_AUTOMATION_ENABLED=}"
  fi
  if [ -n "$SPARKCLAW_BROWSER_CHROMIUM_EXECUTABLE_LINE" ]; then
    export SPARKCLAW_BROWSER_CHROMIUM_EXECUTABLE="${SPARKCLAW_BROWSER_CHROMIUM_EXECUTABLE_LINE#SPARKCLAW_BROWSER_CHROMIUM_EXECUTABLE=}"
  fi
  if [ -n "$SPARKCLAW_BROWSER_PROFILE_DIR_LINE" ]; then
    export SPARKCLAW_BROWSER_PROFILE_DIR="${SPARKCLAW_BROWSER_PROFILE_DIR_LINE#SPARKCLAW_BROWSER_PROFILE_DIR=}"
  fi
  if [ -n "$SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED_LINE" ]; then
    export SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED="${SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED_LINE#SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED=}"
  fi
  if [ -n "$SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER_LINE" ]; then
    export SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER="${SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER_LINE#SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER=}"
  fi
  if [ -n "$SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL_LINE" ]; then
    export SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL="${SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL_LINE#SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL=}"
  fi
  if [ -n "$SPARKCLAW_WEB_SEARCH_ENABLED_LINE" ] && [ -z "${SPARKCLAW_WEB_SEARCH_ENABLED:-}" ]; then
    export SPARKCLAW_WEB_SEARCH_ENABLED="${SPARKCLAW_WEB_SEARCH_ENABLED_LINE#SPARKCLAW_WEB_SEARCH_ENABLED=}"
  fi
  if [ -n "$SPARKCLAW_WEB_SEARCH_PROVIDER_LINE" ] && [ -z "${SPARKCLAW_WEB_SEARCH_PROVIDER:-}" ]; then
    export SPARKCLAW_WEB_SEARCH_PROVIDER="${SPARKCLAW_WEB_SEARCH_PROVIDER_LINE#SPARKCLAW_WEB_SEARCH_PROVIDER=}"
  fi
  if [ -n "$SPARKCLAW_PARALLEL_BASE_URL_LINE" ] && [ -z "${SPARKCLAW_PARALLEL_BASE_URL:-}" ]; then
    export SPARKCLAW_PARALLEL_BASE_URL="${SPARKCLAW_PARALLEL_BASE_URL_LINE#SPARKCLAW_PARALLEL_BASE_URL=}"
  fi
  if [ -n "$SPARKCLAW_PARALLEL_MAX_RESULTS_LINE" ] && [ -z "${SPARKCLAW_PARALLEL_MAX_RESULTS:-}" ]; then
    export SPARKCLAW_PARALLEL_MAX_RESULTS="${SPARKCLAW_PARALLEL_MAX_RESULTS_LINE#SPARKCLAW_PARALLEL_MAX_RESULTS=}"
  fi
  for SPARKCLAW_ENV_NAME in \
    SPARKCLAW_INFINIMESH_INFO_BASE_URL \
    SPARKCLAW_INFINIMESH_INFO_TOKEN_BATCH_SIZE \
    SPARKCLAW_INFINIMESH_INFO_MAX_ATTEMPTS \
    SPARKCLAW_INFINIMESH_INFO_RETRY_BASE_DELAY_MS \
    SPARKCLAW_INFINIMESH_INFO_REQUEST_TIMEOUT_SECONDS \
    SPARKCLAW_INFINIMESH_INFO_RESPONSE_BODY_MAX_BYTES \
    SPARKCLAW_INFINIMESH_INFO_LANGUAGE \
    SPARKCLAW_INFINIMESH_INFO_MAX_SOURCES \
    SPARKCLAW_INFINIMESH_INFO_ENTITLEMENT_PROOF \
    SPARKCLAW_INFINIMESH_INFO_ENTITLEMENT_PROOF_FILE \
    SPARKCLAW_INFINIMESH_INFO_DEVICE_ATTESTATION \
    SPARKCLAW_INFINIMESH_INFO_DEVICE_ATTESTATION_FILE \
    SPARKCLAW_INFINIMESH_INFO_LICENSE_PROOF \
    SPARKCLAW_INFINIMESH_INFO_LICENSE_PROOF_FILE; do
    SPARKCLAW_ENV_LINE="$(grep -E "^${SPARKCLAW_ENV_NAME}=" "$SPARKCLAW_ROOT/.env" | tail -n 1 || true)"
    if [ -n "$SPARKCLAW_ENV_LINE" ] && [ -z "$(printenv "$SPARKCLAW_ENV_NAME" 2>/dev/null || true)" ]; then
      export "$SPARKCLAW_ENV_NAME=${SPARKCLAW_ENV_LINE#*=}"
    fi
  done
fi

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1 || ! command -v go >/dev/null 2>&1; then
  echo "SparkClaw local dev tools were not found under:"
  echo "  $SPARKCLAW_ROOT/.tools"
  return 1 2>/dev/null || exit 1
fi

echo "SparkClaw local dev tools are on PATH."
echo "node: $(node -v)"
echo "npm:  $(npm -v)"
echo "go:   $(go version)"
echo "models: $SPARKCLAW_MODEL_MODE via sparkclaw.infinimesh.cloud"
