#!/usr/bin/env sh

SPARKCLAW_ROOT=""
SPARKCLAW_SEARCH_DIR="$(pwd)"

while [ "$SPARKCLAW_SEARCH_DIR" != "/" ]; do
  if [ -f "$SPARKCLAW_SEARCH_DIR/go.work" ] && [ -f "$SPARKCLAW_SEARCH_DIR/package.json" ]; then
    SPARKCLAW_ROOT="$SPARKCLAW_SEARCH_DIR"
    break
  fi
  SPARKCLAW_SEARCH_DIR="$(dirname -- "$SPARKCLAW_SEARCH_DIR")"
done

if [ -z "$SPARKCLAW_ROOT" ]; then
  echo "SparkClaw repo root was not found."
  return 1 2>/dev/null || exit 1
fi

export SPARKCLAW_MODEL_MODE="${SPARKCLAW_MODEL_MODE:-mock}"
export SPARKCLAW_MODEL_DISABLE_THINKING="${SPARKCLAW_MODEL_DISABLE_THINKING:-true}"
export SPARKCLAW_FAST_BASE_URL="${SPARKCLAW_FAST_BASE_URL:-}"
export SPARKCLAW_FAST_MODEL="${SPARKCLAW_FAST_MODEL:-sparkclaw-fast}"
export SPARKCLAW_FAST_SERVED_NAME="${SPARKCLAW_FAST_SERVED_NAME:-sparkclaw-fast}"
export SPARKCLAW_DEEP_BASE_URL="${SPARKCLAW_DEEP_BASE_URL:-}"
export SPARKCLAW_DEEP_MODEL="${SPARKCLAW_DEEP_MODEL:-sparkclaw-deep}"
export SPARKCLAW_DEEP_SERVED_NAME="${SPARKCLAW_DEEP_SERVED_NAME:-sparkclaw-deep}"
export SPARKCLAW_EMBEDDING_BASE_URL="${SPARKCLAW_EMBEDDING_BASE_URL:-}"
export SPARKCLAW_EMBEDDING_MODEL="${SPARKCLAW_EMBEDDING_MODEL:-sparkclaw-embedding}"
export SPARKCLAW_BROWSER_AUTOMATION_ENABLED="${SPARKCLAW_BROWSER_AUTOMATION_ENABLED:-true}"
export SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST="${SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST:-${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/sparkclaw/browserd/cdp-endpoint}"
export SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE="${SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE:-$SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST}"
export SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED="${SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED:-true}"
export SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER="${SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER:-openclaw-weixin-qr}"
export SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL="${SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL:-https://ilinkai.weixin.qq.com}"

if [ -f "$SPARKCLAW_ROOT/.env.local" ]; then
  SPARKCLAW_BROWSER_AUTOMATION_ENABLED_LINE="$(grep -E '^SPARKCLAW_BROWSER_AUTOMATION_ENABLED=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST_LINE="$(grep -E '^SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED_LINE="$(grep -E '^SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER_LINE="$(grep -E '^SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL_LINE="$(grep -E '^SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  SPARKCLAW_WEB_SEARCH_ENABLED_LINE="$(grep -E '^SPARKCLAW_WEB_SEARCH_ENABLED=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  SPARKCLAW_WEB_SEARCH_PROVIDER_LINE="$(grep -E '^SPARKCLAW_WEB_SEARCH_PROVIDER=' "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
  if [ -n "$SPARKCLAW_BROWSER_AUTOMATION_ENABLED_LINE" ]; then
    export SPARKCLAW_BROWSER_AUTOMATION_ENABLED="${SPARKCLAW_BROWSER_AUTOMATION_ENABLED_LINE#SPARKCLAW_BROWSER_AUTOMATION_ENABLED=}"
  fi
  if [ -n "$SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST_LINE" ]; then
    export SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST="${SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST_LINE#SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST=}"
    export SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE="$SPARKCLAW_BROWSER_CDP_ENDPOINT_FILE_HOST"
  fi
  if [ -n "$SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED_LINE" ]; then
    export SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED="${SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED_LINE#SPARKCLAW_WEIXIN_NOTIFICATION_ENABLED=}"
  fi
  if [ -n "$SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER_LINE" ]; then
    export SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER="${SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER_LINE#SPARKCLAW_WEIXIN_NOTIFICATION_PROVIDER=}"
  fi
  if [ -n "$SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL_LINE" ]; then
    export SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL="${SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL_LINE#SPARKCLAW_WEIXIN_NOTIFICATION_BASE_URL=}"
  fi
  if [ -n "$SPARKCLAW_WEB_SEARCH_ENABLED_LINE" ] && [ -z "${SPARKCLAW_WEB_SEARCH_ENABLED:-}" ]; then
    export SPARKCLAW_WEB_SEARCH_ENABLED="${SPARKCLAW_WEB_SEARCH_ENABLED_LINE#SPARKCLAW_WEB_SEARCH_ENABLED=}"
  fi
  if [ -n "$SPARKCLAW_WEB_SEARCH_PROVIDER_LINE" ] && [ -z "${SPARKCLAW_WEB_SEARCH_PROVIDER:-}" ]; then
    export SPARKCLAW_WEB_SEARCH_PROVIDER="${SPARKCLAW_WEB_SEARCH_PROVIDER_LINE#SPARKCLAW_WEB_SEARCH_PROVIDER=}"
  fi
  for SPARKCLAW_ENV_NAME in \
    SPARKCLAW_INFINIMESH_INFO_BASE_URL \
    SPARKCLAW_INFINIMESH_INFO_TOKEN_BATCH_SIZE \
    SPARKCLAW_INFINIMESH_INFO_MAX_ATTEMPTS \
    SPARKCLAW_INFINIMESH_INFO_RETRY_BASE_DELAY_MS \
    SPARKCLAW_INFINIMESH_INFO_REQUEST_TIMEOUT_SECONDS \
    SPARKCLAW_INFINIMESH_INFO_RESPONSE_BODY_MAX_BYTES \
    SPARKCLAW_INFINIMESH_INFO_LANGUAGE \
    SPARKCLAW_INFINIMESH_INFO_MAX_SOURCES \
    SPARKCLAW_INFINIMESH_INFO_LICENSE_ID \
    SPARKCLAW_INFINIMESH_INFO_LICENSE_KEY \
    SPARKCLAW_INFINIMESH_INFO_LICENSE_KEY_FILE; do
    SPARKCLAW_ENV_LINE="$(grep -E "^${SPARKCLAW_ENV_NAME}=" "$SPARKCLAW_ROOT/.env.local" | tail -n 1 || true)"
    if [ -n "$SPARKCLAW_ENV_LINE" ] && [ -z "$(printenv "$SPARKCLAW_ENV_NAME" 2>/dev/null || true)" ]; then
      export "$SPARKCLAW_ENV_NAME=${SPARKCLAW_ENV_LINE#*=}"
    fi
  done
fi

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1 || ! command -v go >/dev/null 2>&1; then
  echo "SparkClaw requires node, npm, and go on PATH."
  return 1 2>/dev/null || exit 1
fi

echo "SparkClaw development tools are on PATH."
echo "node: $(node -v)"
echo "npm:  $(npm -v)"
echo "go:   $(go version)"
echo "models: $SPARKCLAW_MODEL_MODE"
